# Generated by Django 2.2.15 on 2020-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0112_auto_20201115_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='code feedback'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='compile errors'),
        ),
    ]
