# Generated by Django 2.2.15 on 2020-11-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0113_auto_20201115_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
    ]
