# Generated by Django 2.2.15 on 2020-11-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_remove_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='code feedback'),
        ),
    ]
